# Uncomment the next line to define a global platform for your project
platform :ios, '12.1'

target 'Projet_Smartphone' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Projet_Smartphone
  pod 'SwiftSocket'
end
